// Simple username checks ported from user-scanner (kaifcodec/user-scanner).
// Hard platforms stay on the IntelHub checks in usernameSearch.js.
export const extraUsernameSites = [
    { name: "Airliners.net", uri: "https://www.airliners.net/user/{account}/profile", category: "community", check_type: "status_ok" },
    { name: "Coder Legion", uri: "https://coderlegion.com/user/{account}", category: "community", check_type: "status_ok", display_uri: "https://coderlegion.com/user/{account}" },
    { name: "D3.ru", uri: "https://d3.ru/user/{account}/", category: "community", check_type: "status_ok", display_uri: "https://d3.ru/user/{account}/" },
    { name: "Discourse Meta", uri: "https://meta.discourse.org/u/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://meta.discourse.org/u/{account}" },
    { name: "Ghost Forum", uri: "https://forum.ghost.org/u/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://forum.ghost.org/u/{account}" },
    { name: "Hacker News", uri: "https://hacker-news.firebaseio.com/v0/user/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://news.ycombinator.com/user?id={account}" },
    { name: "Harvard Cyber", uri: "https://cyber.harvard.edu/people/{account}", category: "community", check_type: "status_ok" },
    { name: "Hive", uri: "https://hive.blog/@{account}", category: "community", check_type: "status_ok", display_uri: "https://hive.blog/@{account}" },
    { name: "Instructables", uri: "https://www.instructables.com/member/{account}/", category: "community", check_type: "status_ok" },
    { name: "Jupyter Forum", uri: "https://discourse.jupyter.org/u/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://discourse.jupyter.org/u/{account}" },
    { name: "Mozilla Discourse", uri: "https://discourse.mozilla.org/u/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://discourse.mozilla.org/u/{account}" },
    { name: "Opera Forums", uri: "https://forums.opera.com/api/user/{account}", category: "community", check_type: "json_ok", display_uri: "https://forums.opera.com/user/{account}" },
    { name: "Ubuntu MATE", uri: "https://ubuntu-mate.community/u/{account}.json", category: "community", check_type: "json_ok", display_uri: "https://ubuntu-mate.community/u/{account}" },
    { name: "World Economic Forum", uri: "https://www.weforum.org/people/{account}", category: "community", check_type: "status_ok" },
    { name: "35Photo", uri: "https://35photo.pro/@{account}/", category: "creative", check_type: "status_and_content", valid_text: "Catalogs of professional author" },
    { name: "Behance", uri: "https://www.behance.net/{account}/appreciated", category: "creative", check_type: "status_ok", display_uri: "https://www.behance.net/{account}" },
    { name: "DeviantArt", uri: "https://www.deviantart.com/{account}", category: "creative", check_type: "status_ok" },
    { name: "Dribbble", uri: "https://dribbble.com/{account}/about", category: "creative", check_type: "status_ok", display_uri: "https://dribbble.com/{account}" },
    { name: "Magnific", uri: "https://www.magnific.com/author/{account}", category: "creative", check_type: "status_ok" },
    { name: "Picsart", uri: "https://api.picsart.com/users/show/{account}.json", category: "creative", check_type: "json_ok", display_uri: "https://picsart.com/u/{account}" },
    { name: "Ameblo", uri: "https://ameblo.jp/{account}", category: "creator", check_type: "status_ok", display_uri: "https://ameblo.jp/{account}" },
    { name: "Bio.link", uri: "https://bio.link/{account}", category: "creator", check_type: "status_ok", display_uri: "https://bio.link/{account}" },
    { name: "Bio.site", uri: "https://bio.site/{account}", category: "creator", check_type: "status_ok", display_uri: "https://bio.site/{account}" },
    { name: "Boosty", uri: "https://api.boosty.to/v1/blog/{account}", category: "creator", check_type: "json_ok", display_uri: "https://boosty.to/{account}" },
    { name: "Gumroad", uri: "https://{account}.gumroad.com/", category: "creator", check_type: "status_ok", display_uri: "https://{account}.gumroad.com" },
    { name: "Hashnode", uri: "https://hashnode.com/@{account}", category: "creator", check_type: "status_and_content", valid_text: "Available for</h2>" },
    { name: "Itch.io", uri: "https://itch.io/profile/{account}", category: "creator", check_type: "status_ok", display_uri: "https://itch.io/profile/{account}" },
    { name: "Kaggle", uri: "https://www.kaggle.com/{account}", category: "creator", check_type: "status_ok", display_uri: "https://www.kaggle.com/{account}" },
    { name: "Linktree", uri: "https://linktr.ee/{account}", category: "creator", check_type: "missing_text", display_uri: "https://linktr.ee/{account}", valid_text: "Page Not Found" },
    { name: "Odysee", uri: "https://odysee.com/@{account}", category: "creator", check_type: "status_and_content", valid_text: "/@{account}" },
    { name: "Patreon", uri: "https://www.patreon.com/{account}", category: "creator", check_type: "status_ok", display_uri: "https://www.patreon.com/{account}" },
    { name: "Product Hunt", uri: "https://www.producthunt.com/@{account}", category: "creator", check_type: "status_ok" },
    { name: "Rumble", uri: "https://rumble.com/c/{account}", category: "creator", check_type: "status_ok", display_uri: "https://rumble.com/c/{account}" },
    { name: "Solo.to", uri: "https://solo.to/{account}", category: "creator", check_type: "status_ok", display_uri: "https://solo.to/{account}" },
    { name: "Substack", uri: "https://substack.com/api/v1/user/{account}/public_profile", category: "creator", check_type: "json_ok", display_uri: "https://substack.com/@{account}" },
    { name: "Taplink", uri: "https://taplink.cc/{account}", category: "creator", check_type: "status_ok", display_uri: "https://taplink.cc/{account}" },
    { name: "Vimeo", uri: "https://vimeo.com/api/v2/{account}/info.json", category: "creator", check_type: "json_ok", display_uri: "https://vimeo.com/{account}" },
    { name: "Boot.dev", uri: "https://www.boot.dev/u/{account}", category: "dev", check_type: "status_ok", display_uri: "https://boot.dev/u/{account}" },
    { name: "Codeberg", uri: "https://codeberg.org/api/v1/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://codeberg.org/{account}" },
    { name: "Codecademy", uri: "https://www.codecademy.com/profiles/{account}", category: "dev", check_type: "status_and_content", valid_text: "profiles/{account}" },
    { name: "Coderwall", uri: "https://coderwall.com/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://coderwall.com/{account}" },
    { name: "Codewars", uri: "https://www.codewars.com/api/v1/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://www.codewars.com/users/{account}" },
    { name: "Crates.io", uri: "https://crates.io/api/v1/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://crates.io/users/{account}" },
    { name: "Crowdin", uri: "https://crowdin.com/profile/{account}", category: "dev", check_type: "missing_text", display_uri: "https://crowdin.com/profile/{account}", valid_text: "Page Not Found - Crowdin" },
    { name: "CSSBattle", uri: "https://cssbattle.dev/player/{account}", category: "dev", check_type: "status_and_content", display_uri: "https://cssbattle.dev/player/{account}", valid_text: "cssbattle" },
    { name: "Daily.dev", uri: "https://daily.dev/{account}", category: "dev", check_type: "status_ok" },
    { name: "Dev.to", uri: "https://dev.to/api/users/by_username?url={account}", category: "dev", check_type: "json_ok", display_uri: "https://dev.to/{account}" },
    { name: "Devpost", uri: "https://devpost.com/{account}", category: "dev", check_type: "status_ok", display_uri: "https://devpost.com/{account}" },
    { name: "Docker Hub", uri: "https://hub.docker.com/v2/users/{account}/", category: "dev", check_type: "json_ok", display_uri: "https://hub.docker.com/u/{account}" },
    { name: "Elixir Forum", uri: "https://forum.elixirforum.com/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://forum.elixirforum.com/u/{account}" },
    { name: "F-Droid", uri: "https://forum.f-droid.org/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://forum.f-droid.org/u/{account}" },
    { name: "GitBook", uri: "https://{account}.gitbook.io/", category: "dev", check_type: "missing_text", display_uri: "https://{account}.gitbook.io/", valid_text: "Content owner not found" },
    { name: "Gitea", uri: "https://gitea.com/api/v1/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://gitea.com/{account}" },
    { name: "Gitee", uri: "https://gitee.com/api/v5/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://gitee.com/{account}" },
    { name: "GitLab", uri: "https://gitlab.com/api/v4/users?username={account}", category: "dev", check_type: "json_array", display_uri: "https://gitlab.com/{account}" },
    { name: "HackerRank", uri: "https://www.hackerrank.com/rest/contests/master/hackers/{account}/profile", category: "dev", check_type: "json_ok", display_uri: "https://www.hackerrank.com/{account}" },
    { name: "HashiCorp Discuss", uri: "https://discuss.hashicorp.com/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://discuss.hashicorp.com/u/{account}" },
    { name: "Hex.pm", uri: "https://hex.pm/api/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://hex.pm/users/{account}" },
    { name: "Hugging Face", uri: "https://huggingface.co/api/users/{account}/overview", category: "dev", check_type: "json_ok", display_uri: "https://huggingface.co/{account}" },
    { name: "Kotlin Discuss", uri: "https://discuss.kotlinlang.org/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://discuss.kotlinlang.org/u/{account}" },
    { name: "LuaRocks", uri: "https://luarocks.org/modules/{account}", category: "dev", check_type: "status_ok" },
    { name: "Microsoft Learn", uri: "https://learn.microsoft.com/api/profiles/{account}", category: "dev", check_type: "json_ok", display_uri: "https://learn.microsoft.com/en-us/users/{account}/" },
    { name: "npm", uri: "https://www.npmjs.com/~{account}", category: "dev", check_type: "status_ok", display_uri: "https://www.npmjs.com/~{account}" },
    { name: "Packagist", uri: "https://packagist.org/users/{account}/", category: "dev", check_type: "status_ok" },
    { name: "Python Discuss", uri: "https://discuss.python.org/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://discuss.python.org/u/{account}" },
    { name: "RubyGems", uri: "https://rubygems.org/profiles/{account}", category: "dev", check_type: "status_ok" },
    { name: "Rust Users", uri: "https://users.rust-lang.org/u/{account}.json", category: "dev", check_type: "json_ok", display_uri: "https://users.rust-lang.org/u/{account}" },
    { name: "Scratch", uri: "https://api.scratch.mit.edu/users/{account}", category: "dev", check_type: "json_ok", display_uri: "https://scratch.mit.edu/users/{account}" },
    { name: "SourceForge", uri: "https://sourceforge.net/u/{account}/profile/", category: "dev", check_type: "status_ok", display_uri: "https://sourceforge.net/u/{account}/profile/" },
    { name: "WakaTime", uri: "https://wakatime.com/@{account}", category: "dev", check_type: "status_ok", display_uri: "https://wakatime.com/@{account}" },
    { name: "WordPress", uri: "https://profiles.wordpress.org/{account}/", category: "dev", check_type: "status_ok" },
    { name: "Xakep", uri: "https://xakep.ru/author/{account}/", category: "dev", check_type: "status_ok", display_uri: "https://xakep.ru/author/{account}/" },
    { name: "Buy Me a Coffee", uri: "https://buymeacoffee.com/{account}", category: "donation", check_type: "status_ok", display_uri: "https://buymeacoffee.com/{account}" },
    { name: "Donatello", uri: "https://donatello.to/{account}", category: "donation", check_type: "status_ok" },
    { name: "Ko-fi", uri: "https://ko-fi.com/{account}", category: "donation", check_type: "status_and_content", display_uri: "https://ko-fi.com/{account}", valid_text: "id=\"displayName\"" },
    { name: "Liberapay", uri: "https://liberapay.com/{account}", category: "donation", check_type: "status_ok", display_uri: "https://liberapay.com/{account}" },
    { name: "ADVFN", uri: "https://uk.advfn.com/forum/profile/{account}", category: "finance", check_type: "status_and_content", valid_text: "Profile | ADVFN" },
    { name: "DeStream", uri: "https://api.destream.net/siteapi/v2/live/details/{account}", category: "finance", check_type: "json_ok", display_uri: "https://destream.net/live/{account}" },
    { name: "Fragment", uri: "https://fragment.com/username/{account}", category: "finance", check_type: "status_and_content", display_uri: "https://fragment.com/username/{account}", valid_text: "tm-section-header-status" },
    { name: "Chess.com", uri: "https://api.chess.com/pub/player/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://www.chess.com/member/{account}", lowercase: true },
    { name: "FACEIT", uri: "https://www.faceit.com/api/users/v1/nicknames/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://www.faceit.com/en/players/{account}" },
    { name: "Lichess", uri: "https://lichess.org/api/user/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://lichess.org/@/{account}" },
    { name: "Minecraft", uri: "https://api.mojang.com/minecraft/profile/lookup/name/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://namemc.com/profile/{account}" },
    { name: "Modrinth", uri: "https://api.modrinth.com/v2/user/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://modrinth.com/user/{account}" },
    { name: "osu!", uri: "https://osu.ppy.sh/users/{account}", category: "gaming", check_type: "status_ok", display_uri: "https://osu.ppy.sh/users/{account}" },
    { name: "Roblox", uri: "https://www.roblox.com/user.aspx?username={account}", category: "gaming", check_type: "status_ok", display_uri: "https://www.roblox.com/search/users?keyword={account}" },
    { name: "Speedrun.com", uri: "https://www.speedrun.com/api/v1/users/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://www.speedrun.com/users/{account}" },
    { name: "Steam", uri: "https://steamcommunity.com/id/{account}/", category: "gaming", check_type: "status_and_content", display_uri: "https://steamcommunity.com/id/{account}/", valid_text: "\"steamid\"" },
    { name: "TwitchTracker", uri: "https://twitchtracker.com/{account}", category: "gaming", check_type: "status_and_content", display_uri: "https://twitchtracker.com/{account}", valid_text: "Streamer Overview" },
    { name: "Warframe Market", uri: "https://api.warframe.market/v2/user/{account}", category: "gaming", check_type: "json_ok", display_uri: "https://warframe.market/profile/{account}" },
    { name: "AudioJungle", uri: "https://audiojungle.net/user/{account}", category: "music", check_type: "status_ok", display_uri: "https://audiojungle.net/user/{account}" },
    { name: "Audiomack", uri: "https://audiomack.com/{account}", category: "music", check_type: "status_ok", display_uri: "https://audiomack.com/{account}" },
    { name: "Bandcamp", uri: "https://bandcamp.com/{account}", category: "music", check_type: "status_and_content", display_uri: "https://bandcamp.com/{account}", valid_text: " collection | Bandcamp</title>" },
    { name: "BandLab", uri: "https://www.bandlab.com/api/v1.3/users/{account}", category: "music", check_type: "json_ok", display_uri: "https://www.bandlab.com/{account}" },
    { name: "Discogs", uri: "https://api.discogs.com/users/{account}", category: "music", check_type: "json_ok", display_uri: "https://www.discogs.com/user/{account}" },
    { name: "Freesound", uri: "https://freesound.org/people/{account}/", category: "music", check_type: "missing_text", valid_text: "Page not found" },
    { name: "Last.fm", uri: "https://www.last.fm/user/{account}", category: "music", check_type: "status_ok", display_uri: "https://www.last.fm/user/{account}" },
    { name: "Mixcloud", uri: "https://api.mixcloud.com/{account}/", category: "music", check_type: "json_ok", display_uri: "https://www.mixcloud.com/{account}/" },
    { name: "Myspace", uri: "https://myspace.com/{account}", category: "music", check_type: "status_ok" },
    { name: "SoundCloud", uri: "https://soundcloud.com/{account}", category: "music", check_type: "status_ok", display_uri: "https://soundcloud.com/{account}" },
    { name: "Stats.fm", uri: "https://api.stats.fm/api/v1/users/{account}", category: "music", check_type: "json_ok", display_uri: "https://stats.fm/{account}" },
    { name: "Calendly", uri: "https://calendly.com/api/booking/profiles/{account}", category: "other", check_type: "json_ok", display_uri: "https://calendly.com/{account}" },
    { name: "omg.lol", uri: "https://api.omg.lol/address/{account}/info", category: "other", check_type: "json_ok", display_uri: "https://omg.lol/{account}" },
    { name: "Pastebin", uri: "https://pastebin.com/u/{account}", category: "other", check_type: "status_and_content", valid_text: "info-bar" },
    { name: "Trello", uri: "https://trello.com/1/Members/{account}", category: "other", check_type: "json_ok", display_uri: "https://trello.com/{account}" },
    { name: "Zomato", uri: "https://www.zomato.com/{account}/reviews", category: "other", check_type: "status_ok" },
    { name: "American Thinker", uri: "https://www.americanthinker.com/author/{account}/", category: "political", check_type: "status_ok" },
    { name: "Natural News", uri: "https://naturalnews.com/author/{account}/", category: "political", check_type: "missing_text", valid_text: "The page you are looking for cannot be found" },
    { name: "New America", uri: "https://www.newamerica.org/our-people/{account}/", category: "political", check_type: "missing_text", valid_text: "Page not found" },
    { name: "Fiverr", uri: "https://www.fiverr.com/{account}", category: "shopping", check_type: "status_ok" },
    { name: "7dach", uri: "https://7dach.ru/profile/{account}", category: "social", check_type: "status_and_content", valid_text: "Информация / Профиль" },
    { name: "About.me", uri: "https://about.me/{account}", category: "social", check_type: "status_and_content", valid_text: " | about.me" },
    { name: "AnonUp", uri: "https://anonup.com/@{account}", category: "social", check_type: "status_and_content", display_uri: "https://anonup.com/@{account}", valid_text: "Show followings" },
    { name: "Aparat", uri: "https://www.aparat.com/api/fa/v1/user/user/information/username/{account}", category: "social", check_type: "json_ok", display_uri: "https://www.aparat.com/{account}" },
    { name: "Blogger", uri: "https://{account}.blogspot.com/", category: "social", check_type: "status_ok" },
    { name: "Bluesky", uri: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor={account}", category: "social", check_type: "json_ok", display_uri: "https://bsky.app/profile/{account}", handle_suffix: ".bsky.social" },
    { name: "BuzzFeed", uri: "https://www.buzzfeed.com/{account}", category: "social", check_type: "status_ok" },
    { name: "Carrd", uri: "https://{account}.carrd.co", category: "social", check_type: "missing_text", display_uri: "https://{account}.carrd.co", valid_text: "Sorry, the requested page could not be found." },
    { name: "Dailymotion", uri: "https://api.dailymotion.com/user/{account}?fields=id,username,screenname,description,avatar_720_url,cover_250_url,followers_total,following_total,videos_total,country,created_time,verified,url", category: "social", check_type: "json_ok", display_uri: "https://www.dailymotion.com/{account}" },
    { name: "Foursquare", uri: "https://foursquare.com/{account}", category: "social", check_type: "status_ok" },
    { name: "Giphy", uri: "https://giphy.com/channel/{account}", category: "social", check_type: "status_and_content", display_uri: "https://giphy.com/channel/{account}", valid_text: "giphy://shortcut/channel/" },
    { name: "Goodreads", uri: "https://www.goodreads.com/{account}", category: "social", check_type: "status_ok" },
    { name: "Gravatar", uri: "https://en.gravatar.com/{account}.json", category: "social", check_type: "json_ok", display_uri: "https://gravatar.com/{account}" },
    { name: "Habr", uri: "https://habr.com/ru/users/{account}/", category: "social", check_type: "status_ok" },
    { name: "IFTTT", uri: "https://ifttt.com/p/{account}", category: "social", check_type: "status_ok" },
    { name: "iFunny", uri: "https://ifunny.co/user/{account}", category: "social", check_type: "status_ok", display_uri: "https://ifunny.co/user/{account}" },
    { name: "Imgur", uri: "https://api.imgur.com/account/v1/accounts/{account}?client_id=546c25a59c58ad7&include=trophies%2Cmedallions", category: "social", check_type: "json_ok", display_uri: "https://imgur.com/user/{account}" },
    { name: "Keybase", uri: "https://keybase.io/_/api/1.0/user/lookup.json?usernames={account}", category: "social", check_type: "json_path", display_uri: "https://keybase.io/{account}", valid_json_path: "them.0" },
    { name: "Letterboxd", uri: "https://letterboxd.com/{account}/", category: "social", check_type: "status_and_content", display_uri: "https://letterboxd.com/{account}/", valid_text: "person-summary" },
    { name: "Memory.lol", uri: "https://api.memory.lol/v1/tw/{account}", category: "social", check_type: "json_ok", display_uri: "https://memory.lol/tw/{account}" },
    { name: "Mix", uri: "https://mix.com/{account}", category: "social", check_type: "status_ok", display_uri: "https://mix.com/{account}" },
    { name: "Mssg.me", uri: "https://mssg.me/{account}", category: "social", check_type: "status_ok", display_uri: "https://mssg.me/{account}" },
    { name: "MyAnimeList", uri: "https://myanimelist.net/profile/{account}", category: "social", check_type: "missing_text", display_uri: "https://myanimelist.net/profile/{account}", valid_text: "not found" },
    { name: "OK.ru", uri: "https://ok.ru/{account}", category: "social", check_type: "status_ok" },
    { name: "OpenStreetMap", uri: "https://www.openstreetmap.org/user/{account}", category: "social", check_type: "status_and_content", display_uri: "https://www.openstreetmap.org/user/{account}", valid_text: "Mapper since" },
    { name: "Speaker Deck", uri: "https://speakerdeck.com/{account}", category: "social", check_type: "missing_text", display_uri: "https://speakerdeck.com/{account}", valid_text: "User Not Found" },
    { name: "Sports Tracker", uri: "https://api.sports-tracker.com/apiserver/v1/user/name/{account}", category: "social", check_type: "json_ok", display_uri: "https://www.sports-tracker.com/view_profile/{account}" },
    { name: "Telegram", uri: "https://t.me/{account}", category: "social", check_type: "status_and_content", display_uri: "https://t.me/{account}", valid_text: "tgme_page_extra" },
    { name: "Tenor", uri: "https://tenor.com/users/{account}", category: "social", check_type: "missing_text", display_uri: "https://tenor.com/users/{account}", valid_text: "page not found" },
    { name: "Virgool", uri: "https://virgool.io/@{account}", category: "social", check_type: "status_ok" },
    { name: "VK", uri: "https://vk.com/{account}", category: "social", check_type: "status_ok", display_uri: "https://vk.com/{account}" },
    { name: "Weebly", uri: "https://{account}.weebly.com/", category: "social", check_type: "status_ok" },
];
